/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package expenseManage;

/**
 *
 * @author hikaru
 */
public class User extends javax.swing.JFrame {

    /**
     * Creates new form Loginpage
     */
    public User() {
        initComponents();
    }

    public javax.swing.JButton Button() {
        return Button;
    }
    
    public javax.swing.JButton InfoButton() {
        return InfoButton;
    }
    
    public javax.swing.JLabel InfoButtonLabel() {
        return InfoButtonLabel;
    }

    public javax.swing.JLabel InfoLabel() {
        return InfoLabel;
    }

    public javax.swing.JTextField UserField() {
        return UserField;
    }

    public javax.swing.JTextField PassField() {
        return PassField;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        UserPanel = new javax.swing.JPanel();
        UserField = new javax.swing.JTextField();
        PassField = new javax.swing.JTextField();
        Button = new javax.swing.JButton();
        UserLabel = new javax.swing.JLabel();
        PassLabel = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        InfoLabel = new javax.swing.JLabel();
        InfoButtonLabel = new javax.swing.JLabel();
        InfoButton = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        jLabel3.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(495, 631));
        setMinimumSize(new java.awt.Dimension(495, 631));

        UserPanel.setBackground(new java.awt.Color(153, 255, 153));
        UserPanel.setMaximumSize(new java.awt.Dimension(495, 631));
        UserPanel.setMinimumSize(new java.awt.Dimension(495, 631));
        UserPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UserField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserFieldActionPerformed(evt);
            }
        });
        UserPanel.add(UserField, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 194, 411, 45));
        UserPanel.add(PassField, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 276, 411, 45));

        Button.setBackground(new java.awt.Color(51, 204, 0));
        Button.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        Button.setForeground(new java.awt.Color(0, 51, 0));
        Button.setText("Button");
        Button.setFocusable(false);
        Button.setRolloverEnabled(false);
        Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonActionPerformed(evt);
            }
        });
        UserPanel.add(Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 352, 411, 46));

        UserLabel.setFont(new java.awt.Font("Albert Sans", 0, 15)); // NOI18N
        UserLabel.setForeground(new java.awt.Color(0, 51, 0));
        UserLabel.setText("Username");
        UserPanel.add(UserLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 168, -1, -1));

        PassLabel.setFont(new java.awt.Font("Albert Sans", 0, 15)); // NOI18N
        PassLabel.setForeground(new java.awt.Color(0, 51, 0));
        PassLabel.setText("Password");
        UserPanel.add(PassLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 251, -1, -1));

        Logo.setText("Logo here if wala delete nalang to");
        UserPanel.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 37, 411, 95));

        InfoLabel.setFont(new java.awt.Font("Albert Sans", 0, 15)); // NOI18N
        InfoLabel.setForeground(new java.awt.Color(40, 92, 15));
        InfoLabel.setText("InfoText");
        UserPanel.add(InfoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 431, 230, -1));

        InfoButtonLabel.setFont(new java.awt.Font("Albert Sans", 1, 15)); // NOI18N
        InfoButtonLabel.setForeground(new java.awt.Color(40, 92, 15));
        InfoButtonLabel.setText("Info");
        UserPanel.add(InfoButtonLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 450, 70, -1));

        InfoButton.setBorderPainted(false);
        InfoButton.setContentAreaFilled(false);
        InfoButton.setFocusPainted(false);
        InfoButton.setFocusable(false);
        InfoButton.setRolloverEnabled(false);
        UserPanel.add(InfoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, 60, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(UserPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(UserPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UserFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserFieldActionPerformed

    private void ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button;
    private javax.swing.JButton InfoButton;
    private javax.swing.JLabel InfoButtonLabel;
    private javax.swing.JLabel InfoLabel;
    private javax.swing.JLabel Logo;
    private javax.swing.JTextField PassField;
    private javax.swing.JLabel PassLabel;
    private javax.swing.JTextField UserField;
    private javax.swing.JLabel UserLabel;
    private javax.swing.JPanel UserPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
